FROM node:12

WORKDIR /usr/src/app

RUN npm install -g @angular/cli@11

COPY package*.json ./

RUN npm install

COPY . .

EXPOSE 4200

CMD ["npm", "start", "--", "--host", "0.0.0.0", "--poll", "500"]
