/**
 * Mi API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ActualizarRutaDto { 
    idRuta?: number;
    descripcion?: string | null;
    rutaElegida?: string | null;
    idSKU?: number;
    idListadoEquipos?: number;
    tipoRuta?: string | null;
    idRestriccionRuta?: number;
}

