/**
 * Mi API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ActualizarRestriccionEquiposDto { 
    id?: number;
    descripcion?: string | null;
    estado?: boolean;
    idEquipo?: number;
    tipoRestriccion?: string | null;
    idUnidadMedida?: number;
    valor?: number;
    prioridad?: number;
    idRestriccionLavados?: number;
}

