/**
 * Mi API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ActualizarRestriccionLavadoDto { 
    idRestriccionLavados?: number;
    descripcion?: string | null;
    estado?: boolean;
    idFamilia?: number;
    idMaquina?: string | null;
    tipoLavado?: string | null;
    frecuenciaLavado?: number;
    tiempoLavado?: number;
}

