/**
 * Mi API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ActualizarFamiliaProductosDto { 
    idFamilia?: number;
    nombre?: string | null;
    estado?: boolean | null;
    tiempoFormulacion?: number | null;
}

