/**
 * Mi API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ActualizarRoleModuloPermisoDto } from './actualizarRoleModuloPermisoDto';


export interface ActualizarRoleDto { 
    id?: number;
    nombre?: string | null;
    estado?: boolean;
    permisos?: Array<ActualizarRoleModuloPermisoDto> | null;
}

