/**
 * Mi API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ActualizarMaquinaDto { 
    idMaquina?: string | null;
    idTipo?: number | null;
    idZona?: number | null;
    nombre?: string | null;
    personalRequeridoMaquina?: number | null;
    personalRequeridoEmbalaje?: number | null;
}

