/**
 * Mi API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ActualizarEquipoDto { 
    idEquipo?: number;
    tipo?: string | null;
    estado?: boolean;
    descripcion?: string | null;
    zonaUbicacion?: string | null;
    restriccionEquipos?: number;
}

