/**
 * Mi API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ModuloDto } from './moduloDto';


export interface CrearRoleDto {
    nombre?: string | null;
    estado?: boolean;
    idUsuario?: number;
    modulos?: Array<ModuloDto> | null;
}

