/**
 * Mi API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CrearUsuarioDto { 
    correoElectronico?: string | null;
    cedula?: number;
    nombre?: string | null;
    apellido?: string | null;
    cargo?: string | null;
    clave?: string | null;
    foto?: string | null;
    roles?: Array<number> | null;
}

