/**
 * Mi API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CrearPlaneacionProduccionDto { 
    idProducto?: string | null;
    semana?: string | null;
    cantidadesProducir?: number;
}

