/**
 * Mi API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CrearRestriccionRutaDto { 
    descripcion?: string | null;
    idMaquina?: string | null;
    idFamilia?: number | null;
    tipoRestriccion?: string | null;
    unidadMedida?: string | null;
    valor?: string | null;
    prioridad?: number | null;
}

