/**
 * Mi API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CrearPlaneacionProduccionDto } from './crearPlaneacionProduccionDto';


export interface CrearPlaneacionProduccionDtoIEnumerableDataResponse { 
    exito?: string | null;
    datos?: Array<CrearPlaneacionProduccionDto> | null;
}

