/**
 * Mi API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CrearRutaDto { 
    nombre?: string | null;
    idFamilia?: number | null;
    idLinea?: number | null;
    idMaquinas?: string | null;
    tipoRuta?: string | null;
    idRestriccionRuta?: number | null;
    rutaSugeridaEmpresa?: boolean | null;
    rutaSugeridaModelo?: boolean | null;
    fechaCreacion?: string | null;
    rutaElegida?: number | null;
}

