/**
 * Mi API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CrearRutaDto { 
    descripcion?: string | null;
    rutaElegida?: string | null;
    idSku?: number | null;
    idListadoEquipos?: number | null;
    tipoRuta?: string | null;
    idRestriccionRuta?: number | null;
}

