/**
 * Mi API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CrearHistoricoRutasDto { 
    idRutaPrediccion?: number | null;
    idRuta?: number | null;
    semanaProduccion?: string | null;
    idFamilia?: number;
    rutaElegida?: boolean;
    sugerencia?: boolean;
    precision?: number;
}

