/**
 * Mi API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ActualizarRoleDtoModulosInner } from './actualizarRoleDtoModulosInner';


export interface CrearRoleDto { 
    nombre?: string | null;
    estado?: boolean;
    modulos?: Array<ActualizarRoleDtoModulosInner> | null;
}

