/**
 * Mi API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FamiliaProductoDto } from './familiaProductoDto';


export interface FamiliaProductoDtoIEnumerableDataResponse { 
    exito?: string | null;
    datos?: Array<FamiliaProductoDto> | null;
}

