/**
 * Mi API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HistoricoRutaDto } from './historicoRutaDto';


export interface HistoricoRutaDtoIEnumerableDataResponse { 
    exito?: string | null;
    datos?: Array<HistoricoRutaDto> | null;
}

