/**
 * Mi API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HistoricoRutaDto } from './historicoRutaDto';


export interface HistoricoRutaDtoPaginatedData { 
    page?: number;
    totalItemCount?: number;
    data?: Array<HistoricoRutaDto> | null;
}

