/**
 * Mi API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface HistoricoRutaDto { 
    id?: number;
    idRutaPrediccion?: number | null;
    semanaProduccion?: string | null;
    idFamilia?: number;
    nombreFamilia?: string | null;
    rutaElegida?: boolean;
    fechaCreacion?: string;
    idRuta?: number | null;
    equipmentList?: Array<string> | null;
    restrictionList?: Array<string> | null;
}

