/**
 * Mi API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HistoricoRutaDtoPaginatedData } from './historicoRutaDtoPaginatedData';


export interface HistoricoRutaDtoPaginatedDataDataResponse { 
    exito?: string | null;
    datos?: HistoricoRutaDtoPaginatedData;
}

