/**
 * Mi API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface HistoricoRutaDto { 
    idFamilia?: number;
    nombreFamilia?: string | null;
    idRuta?: number;
    readonly nombreRuta?: string | null;
    equipmentList?: Array<string> | null;
    restriction?: string | null;
    usos?: number;
}

