/**
 * Mi API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { InitialProductFamilyRoutePrioritizationRequest } from './initialProductFamilyRoutePrioritizationRequest';


export interface InitialRoutePrioritizationRequest { 
    semana?: string | null;
    productFamilyRoutePrioritizations?: Array<InitialProductFamilyRoutePrioritizationRequest> | null;
}

