/**
 * Mi API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Int32ReferenceDto } from './int32ReferenceDto';


export interface Int32ReferenceDtoIEnumerableDataResponse { 
    exito?: string | null;
    datos?: Array<Int32ReferenceDto> | null;
}

