/**
 * Mi API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { LineasProduccionDto } from './lineasProduccionDto';


export interface LineasProduccionDtoIEnumerableDataResponse { 
    exito?: string | null;
    datos?: Array<LineasProduccionDto> | null;
}

