/**
 * Mi API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MaquinaDto } from './maquinaDto';


export interface MaquinaDtoListDataResponse { 
    exito?: string | null;
    datos?: Array<MaquinaDto> | null;
}

