/**
 * Mi API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DateOnly } from './dateOnly';


export interface MaquinaDto { 
    idMaquina?: string | null;
    idTipo?: number | null;
    nombreTipo?: string | null;
    idZona?: number | null;
    nombreZona?: string | null;
    nombre?: string | null;
    personalRequeridoMaquina?: number | null;
    personalRequeridoEmbalaje?: number | null;
    estado?: string | null;
    fechaCreacion?: DateOnly;
}

