/**
 * Mi API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TblModulos } from './tblModulos';
import { TblPermiso } from './tblPermiso';


export interface ModulosRolesPermisosDto { 
    modulos?: Array<TblModulos> | null;
    permisos?: Array<TblPermiso> | null;
    mensaje?: string | null;
}

