/**
 * Mi API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PermisosRoleDto } from './permisosRoleDto';


export interface ModuloDto {
    idModulo?: number;
    permisos?: Array<PermisosRoleDto> | null;
}

