/**
 * Mi API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TblPermiso } from './tblPermiso';
import { TblModulosUsuario } from './tblModulosUsuario';


export interface ModulosRolesPermisosDto { 
    modulos?: Array<TblModulosUsuario> | null;
    permisos?: Array<TblPermiso> | null;
    mensaje?: string | null;
}

