/**
 * Mi API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PlaneacionProduccionDto } from './planeacionProduccionDto';


export interface PlaneacionProduccionDtoIEnumerableDataResponse { 
    exito?: string | null;
    datos?: Array<PlaneacionProduccionDto> | null;
}

