/**
 * Mi API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PrediccionesRutasDto { 
    idPrediccion?: number;
    idFamilia?: number | null;
    idRuta?: number | null;
    idProducto?: string | null;
    optimalScore?: number | null;
    fechaPrediccion?: string | null;
}

