/**
 * Mi API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PrediccionesRutasDto } from './prediccionesRutasDto';


export interface PrediccionesRutasDtoIEnumerableDataResponse { 
    exito?: string | null;
    datos?: Array<PrediccionesRutasDto> | null;
}

