/**
 * Mi API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ProductoDto } from './productoDto';


export interface ProductoDtoDataResponse { 
    exito?: string | null;
    datos?: ProductoDto;
}

