/**
 * Mi API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ProductoDto { 
    idProducto?: string | null;
    familia?: string | null;
    nombre?: string | null;
    presentacion?: string | null;
    volumen?: string | null;
    fechaCreacion?: string | null;
    estado?: boolean;
}

