/**
 * Mi API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ProductRoutePrioritizationRequest { 
    cantidades_producir?: number;
    familia?: number;
    sku?: string | null;
}

