/**
 * Mi API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RestriccionMaquinaDto } from './restriccionMaquinaDto';


export interface RestriccionMaquinaDtoDataResponse { 
    exito?: string | null;
    datos?: RestriccionMaquinaDto;
}

