/**
 * Mi API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RestriccionLavadoDto } from './restriccionLavadoDto';


export interface RestriccionLavadoDtoIEnumerableDataResponse { 
    exito?: string | null;
    datos?: Array<RestriccionLavadoDto> | null;
}

