/**
 * Mi API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface RestriccionLavadoDto { 
    id?: number;
    'descripción'?: string | null;
    estado?: boolean;
    fechaCreacion?: string;
    idFamilia?: number | null;
    tipoLavado?: string | null;
    frecuenciaLavado?: number | null;
    tiempoLavado?: number | null;
    prioridad?: number;
}

