/**
 * Mi API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RestriccionRutasDto } from './restriccionRutasDto';


export interface RestriccionRutasDtoIEnumerableDataResponse { 
    exito?: string | null;
    datos?: Array<RestriccionRutasDto> | null;
}

