/**
 * Mi API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ActualizarRoleDtoModulosInner } from './actualizarRoleDtoModulosInner';
import { DateOnly } from './dateOnly';


export interface RoleDto { 
    id?: number;
    nombre?: string | null;
    estado?: boolean;
    fechaCreacion?: DateOnly;
    modulos?: Array<ActualizarRoleDtoModulosInner> | null;
}

