/**
 * Mi API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DateOnly } from './dateOnly';
import { RoleModuloPermisoDto } from './roleModuloPermisoDto';
import { UsuarioModuloDto } from './usuarioModuloDto';


export interface RoleDto { 
    id?: number;
    nombre?: string | null;
    estado?: boolean;
    fechaCreacion?: DateOnly;
    permisos?: Array<RoleModuloPermisoDto> | null;
    modulos?: Array<UsuarioModuloDto> | null;
}

