/**
 * Mi API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RoleModuloPermisoDto } from './roleModuloPermisoDto';


export interface RoleDto { 
    id?: number;
    nombre?: string | null;
    estado?: boolean;
    fechaCreacion?: string;
    permisos?: Array<RoleModuloPermisoDto> | null;
}

