/**
 * Mi API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ProductRoutePrioritizationRequest } from './productRoutePrioritizationRequest';


export interface RoutePrioritizationRequest { 
    productos?: Array<ProductRoutePrioritizationRequest> | null;
    semana?: string | null;
}

