/**
 * Mi API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RutaDto } from './rutaDto';


export interface RutaDtoIEnumerableDataResponse { 
    exito?: string | null;
    datos?: Array<RutaDto> | null;
}

