/**
 * Mi API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface RutaDto { 
    idRuta?: number;
    nombre?: string | null;
    idFamilia?: number | null;
    tipoRuta?: string | null;
    idLinea?: number | null;
    idRestriccionRuta?: number | null;
}

