/**
 * Mi API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SolicitudProduccionDto { 
    descripcion?: string | null;
    idSKU?: number;
    semana?: number;
    unidadesProducir?: number;
    estado?: boolean;
}

