/**
 * Mi API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface StringPaginatedData { 
    page?: number;
    totalItemCount?: number;
    data?: Array<string> | null;
}

