/**
 * Mi API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { StringPaginatedData } from './stringPaginatedData';


export interface StringPaginatedDataDataResponse { 
    exito?: string | null;
    datos?: StringPaginatedData;
}

