/**
 * Mi API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TblFamiliaProductos } from './tblFamiliaProductos';


export interface TblCambiosCiclosIntermedios { 
    id?: number;
    idFamiliaProceso?: number | null;
    idFamiliaCambio?: number | null;
    tiempoCambioHoras?: number | null;
    familiaProcesoNavigation?: TblFamiliaProductos;
    familiaCambioNavigation?: TblFamiliaProductos;
}

