/**
 * Mi API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface TblEquipo { 
    idEquipo?: number;
    Tipo?: string | null;
    Estado?: boolean;
    FechaCreacion?: string;
    Descripcion?: string | null;
    ZonaUbicacion?: string | null;
    RestriccionEquipos?: number;
}

