/**
 * Mi API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TblRutum } from './tblRutum';
import { DateOnly } from './dateOnly';


export interface TblHistoriaProduccion { 
    idHistorial?: number;
    idRuta?: number | null;
    cantidad?: number | null;
    fecha?: DateOnly;
    idRutaNavigation?: TblRutum;
}

