/**
 * Mi API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TblUsuario } from './tblUsuario';


export interface TblIntentosDeLogin { 
    id?: number;
    idUsuario?: number;
    intentosFallidos?: number;
    fechaUltimoIntento?: string;
    cuentaBloqueada?: boolean;
    fechaFinBloqueo?: string | null;
    idUsuarioNavigation?: TblUsuario;
}

