/**
 * Mi API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TblUsuarios } from './tblUsuarios';


export interface TblIntentosDeLogin { 
    id?: number;
    idUsuario?: number;
    intentosFallidos?: number;
    fechaUltimoIntento?: string;
    cuentaBloqueada?: boolean;
    fechaFinBloqueo?: string | null;
    usuarios?: TblUsuarios;
}

