/**
 * Mi API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TblRuta } from './tblRuta';
import { TblMaquinas } from './tblMaquinas';


export interface TblListadoEquiposRuta { 
    idMaquina?: string | null;
    idRuta?: number;
    orden?: number;
    maquinas?: TblMaquinas;
    rutas?: TblRuta;
}

