/**
 * Mi API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TblRoles } from './tblRoles';
import { TblUsuarios } from './tblUsuarios';


export interface TblModulosUsuario { 
    id?: number;
    idRole?: number;
    idUsuario?: number;
    idRolNavigation?: TblRoles;
    idUsuarioNavigation?: TblUsuarios;
}

