/**
 * Mi API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TblPrediccionRutaYTblRutaDto } from './tblPrediccionRutaYTblRutaDto';


export interface TblPrediccionRutaYTblRutaDtoRespuestaPaginacion { 
    paginaActual?: number;
    tamanoPagina?: number;
    totalPaginas?: number;
    totalRegistros?: number;
    datos?: Array<TblPrediccionRutaYTblRutaDto> | null;
}

