/**
 * Mi API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface TblPrediccionRutaYTblRutaDto { 
    id?: number;
    descripcion?: string | null;
    idFamilia?: number | null;
    tipoRuta?: string | null;
    linea?: number | null;
    restriccion?: number | null;
}

