/**
 * Mi API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TblPrediccionRutaYTblRutaDto } from './tblPrediccionRutaYTblRutaDto';


export interface TblPrediccionRutaYTblRutaDtoListDataResponse { 
    exito?: string | null;
    datos?: Array<TblPrediccionRutaYTblRutaDto> | null;
}

