/**
 * Mi API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TblPermiso } from './tblPermiso';
import { TblRoles } from './tblRoles';


export interface TblRolesPermiso { 
    id?: number;
    idRol?: number | null;
    idPermiso?: number | null;
    idPermisoNavigation?: TblPermiso;
    rol?: TblRoles;
    permiso?: TblPermiso;
}

