/**
 * Mi API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TblRutum } from './tblRutum';
import { TblUnidadMedidum } from './tblUnidadMedidum';
import { TblEquipo } from './tblEquipo';


export interface TblRestriccionRutum { 
    idRestriccionRuta?: number;
    descripcion?: string | null;
    idEquipo?: number | null;
    tipoRestriccion?: string | null;
    idUnidadMedida?: number;
    valor?: number | null;
    prioridad?: number | null;
    idEquipoNavigation?: TblEquipo;
    idUnidadMedidaNavigation?: TblUnidadMedidum;
    tblRuta?: Array<TblRutum> | null;
}

