/**
 * Mi API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TblPermiso } from './tblPermiso';
import { TblRole } from './tblRole';


export interface TblRolesPermiso { 
    id?: number;
    idRol?: number;
    idPermiso?: number;
    idPermisoNavigation?: TblPermiso;
    idRolNavigation?: TblRole;
}

