/**
 * Mi API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TblRestriccionRutum } from './tblRestriccionRutum';
import { TblListadoEquiposRutum } from './tblListadoEquiposRutum';
import { TblHistoriaProduccion } from './tblHistoriaProduccion';


export interface TblRutum { 
    idRuta?: number;
    descripcion?: string | null;
    rutaElegida?: string | null;
    fechaSolicitud?: string;
    idSku?: number | null;
    idListadoEquipos?: number | null;
    tipoRuta?: string | null;
    idRestriccionRuta?: number | null;
    idListadoEquiposNavigation?: TblListadoEquiposRutum;
    idRestriccionRutaNavigation?: TblRestriccionRutum;
    tblHistoriaProduccions?: Array<TblHistoriaProduccion> | null;
}

