/**
 * Mi API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TblModulosUsuario } from './tblModulosUsuario';


export interface TblRoles { 
    id?: number;
    nombre?: string | null;
    estado?: boolean | null;
    fechaCreacion?: string;
    tblModulosUsuarios?: Array<TblModulosUsuario> | null;
}

