/**
 * Mi API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TblFamiliaProductos } from './tblFamiliaProductos';
import { TblListadoEquiposRuta } from './tblListadoEquiposRuta';
import { TblLineasProduccion } from './tblLineasProduccion';
import { TblMaquinas } from './tblMaquinas';
import { TblRestriccionRuta } from './tblRestriccionRuta';


export interface TblRuta { 
    idRuta?: number;
    nombre?: string | null;
    idFamilia?: number | null;
    idLinea?: number | null;
    idMaquinas?: string | null;
    tipoRuta?: string | null;
    idRestriccionRuta?: number | null;
    rutaSugeridaEmpresa?: boolean | null;
    rutaSugeridaModelo?: boolean | null;
    fechaCreacion?: string | null;
    rutaElegida?: number | null;
    idListadoEquipos?: number | null;
    equipoRuta?: Array<TblListadoEquiposRuta> | null;
    familia?: TblFamiliaProductos;
    linea?: TblLineasProduccion;
    maquinas?: TblMaquinas;
    restriccionRuta?: TblRestriccionRuta;
}

