/**
 * Mi API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TblFamiliaProductos } from './tblFamiliaProductos';
import { TblMaquinas } from './tblMaquinas';


export interface TblRestriccionRuta { 
    idRestriccionRuta?: number;
    descripcion?: string | null;
    idMaquina?: string | null;
    idFamilia?: number | null;
    tipoRestriccion?: string | null;
    unidadMedida?: string | null;
    valor?: string | null;
    prioridad?: number | null;
    fechaCreacion?: string | null;
    maquina?: TblMaquinas;
    familia?: TblFamiliaProductos;
}

