/**
 * Mi API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TblUnidadMedidum } from './tblUnidadMedidum';
import { TblEquipo } from './tblEquipo';
import { TblRestriccionLavados } from './tblRestriccionLavados';


export interface TblRestriccionEquipo { 
    id?: number;
    descripcion?: string | null;
    estado?: boolean;
    fechaCreacion?: string;
    idEquipo?: number | null;
    tipoRestriccion?: string | null;
    idUnidadMedida?: number;
    valor?: number | null;
    prioridad?: number | null;
    idRestriccionLavados?: number | null;
    idEquipoNavigation?: TblEquipo;
    idRestriccionLavadosNavigation?: TblRestriccionLavados;
    idUnidadMedidaNavigation?: TblUnidadMedidum;
}

