/**
 * Mi API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TblSkumaestra } from './tblSkumaestra';


export interface TblSolicitudesProduccion { 
    idSolicitudes?: number;
    descripcion?: string | null;
    idSku?: number;
    semana?: number;
    unidadesProducir?: number;
    estado?: boolean;
    fecha?: string;
    idSkuNavigation?: TblSkumaestra;
}

