/**
 * Mi API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TblSolicitudesProduccion } from './tblSolicitudesProduccion';
import { TblSkufamilia } from './tblSkufamilia';


export interface TblSkumaestra { 
    idSku?: number;
    idFamilia?: number;
    referencia?: string | null;
    estado?: boolean;
    fechaCreacion?: string;
    presentacion?: string | null;
    volumen?: string | null;
    idFamiliaNavigation?: TblSkufamilia;
    tblSolicitudesProduccions?: Array<TblSolicitudesProduccion> | null;
}

