/**
 * Mi API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TblModulosUsuario } from './tblModulosUsuario';


export interface TblUsuario { 
    id?: number;
    correoElectronico?: string | null;
    cedula?: number | null;
    nombre?: string | null;
    apellido?: string | null;
    cargo?: string | null;
    fechaIngreso?: string;
    ultimoAcceso?: string;
    clave?: string | null;
    activo?: boolean;
    tblModulosUsuarios?: Array<TblModulosUsuario> | null;
}

