/**
 * Mi API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TblRoles } from './tblRoles';
import { TblUsuario } from './tblUsuario';


export interface TblUsuarioRol { 
    usuariosId?: number;
    usuario?: TblUsuario;
    rolesId?: number;
    role?: TblRoles;
}

