/**
 * Mi API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DateOnly } from './dateOnly';
import { TblIntentosDeLogin } from './tblIntentosDeLogin';
import { TblModulosUsuario } from './tblModulosUsuario';


export interface TblUsuario { 
    id?: number;
    correoElectronico?: string | null;
    cedula?: number;
    nombre?: string | null;
    apellido?: string | null;
    cargo?: string | null;
    fechaIngreso?: DateOnly;
    ultimoAcceso?: DateOnly;
    clave?: string | null;
    activo?: boolean;
    foto?: string | null;
    tblIntentosDeLogins?: Array<TblIntentosDeLogin> | null;
    tblModulosUsuarios?: Array<TblModulosUsuario> | null;
}

