/**
 * Mi API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TipoMaquinaDto } from './tipoMaquinaDto';


export interface TipoMaquinaDtoDataResponse { 
    exito?: string | null;
    datos?: TipoMaquinaDto;
}

