/**
 * Mi API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PermisosDto } from './permisosDto';


export interface UsuarioModuloDto { 
    id?: number;
    nombreModulo?: string | null;
    permisos?: Array<PermisosDto> | null;
}

