/**
 * Mi API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UsuariosDto } from './usuariosDto';


export interface UsuariosDtoDataResponse { 
    exito?: string | null;
    datos?: UsuariosDto;
}

