/**
 * Mi API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UsuariosDto } from './usuariosDto';


export interface UsuariosDtoIEnumerableDataResponse { 
    exito?: string | null;
    datos?: Array<UsuariosDto> | null;
}

