/**
 * Mi API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UsuariosDto {
    id?: number | null;
    cedula?: number | null;
    nombre?: string | null;
    apellido?: string | null;
    cargo?: string | null;
    clave?: string | null;
    activo?: boolean;
    roles?: Array<number> | null;
}

