/**
 * Mi API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface VwPrediccionesRutasFamiliasProductosDto { 
    id?: number;
    prediccionIdFamilia?: number | null;
    ruta?: number | null;
    producto?: string | null;
    optimalScore?: number | null;
    fechaPrediccion?: string | null;
    nombreFamilia?: string | null;
    estado?: boolean | null;
    tiempoFormulacion?: number | null;
    fechaCreacion?: string | null;
}

