/**
 * Mi API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ZonaDto } from './zonaDto';


export interface ZonaDtoDataResponse { 
    exito?: string | null;
    datos?: ZonaDto;
}

