/**
 * Apis_Optimizacion
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface TblListadoEquiposRutum { 
    IdMaquina?: string | null;
    IdRuta?: number | null;
    Orden?: number | null;
    nombreRuta?: string | null;
    nombreEquipo?: string | null;
}

