/**
 * Apis_Optimizacion
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DateOnly } from './dateOnly';


export interface TblMaquina { 
    IdMaquinas?: string | null;
    IdTipo?: number | null;
    IdZona?: number | null;
    Nombre?: string | null;
    PersonalRequeridoMaquina?: number | null;
    PersonalRequeridoEmbalaje?: number | null;
    Estado?: string | null;
    FechaCreacion?: DateOnly;
    TipoEquipoNombre?: string | null;
    ZonaNombre?: string | null;
}

