/**
 * Apis_Optimizacion
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface TblRestriccionLavado { 
    IdRestriccionLavados?: number | null;
    Descripcion?: string | null;
    IdFamilia?: number | null;
    IdMaquina?: string | null;
    TipoLavado?: string | null;
    FrecuenciaLavado?: number | null;
    Tiempolavado?: number | null;
    Estado?: boolean | null;
    FechaCreacion?: string | null;
    familiaNombre?: string | null;
    nombreMaquina?: string | null;
    personalRequeridoEmbalaje?: number | null;
    personalRequeridoMaquina?: number | null;
    zonaNombre?: string | null;
    tipoMaquina?: string | null;
}

