/**
 * Apis_Optimizacion
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface TblRestriccionRutum { 
    IdRestriccionRuta?: number | null;
    Descripcion?: string | null;
    IdMaquina?: string | null;
    IdFamilia?: number | null;
    TipoRestriccion?: string | null;
    UnidadMedida?: string | null;
    valor?: string | null;
    Prioridad?: number | null;
    FechaCreacion?: string | null;
    familiaNombre?: string | null;
    maquinaNombre?: string | null;
}

