/**
 * Apis_Optimizacion
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface TblTipoMaquina { 
    IdTipoMaquina?: number | null;
    NombreTipo?: string | null;
}

