/**
 * Apis_Optimizacion
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface TblUnidadesProduccion { 
    IProducto?: string | null;
    IdFamilia?: number | null;
    Semana?: string | null;
    CantidadProduccir?: number | null;
    Estado?: boolean | null;
    nombreFamilia?: string | null;
    nombreProducto?: string | null;
}

