export * from './familiaProductos.service';
import { FamiliaProductosService } from './familiaProductos.service';
export * from './lineasProduccion.service';
import { LineasProduccionService } from './lineasProduccion.service';
export * from './login.service';
import { LoginService } from './login.service';
export * from './maestraFamilia.service';
import { MaestraFamiliaService } from './maestraFamilia.service';
export * from './maquinas.service';
import { MaquinasService } from './maquinas.service';
export * from './modulosRolesPermisos.service';
import { ModulosRolesPermisosService } from './modulosRolesPermisos.service';
export * from './planeacionProduccion.service';
import { PlaneacionProduccionService } from './planeacionProduccion.service';
export * from './productos.service';
import { ProductosService } from './productos.service';
export * from './restriccionDeLavado.service';
import { RestriccionDeLavadoService } from './restriccionDeLavado.service';
export * from './restriccionMaquinas.service';
import { RestriccionMaquinasService } from './restriccionMaquinas.service';
export * from './restriccionRutas.service';
import { RestriccionRutasService } from './restriccionRutas.service';
export * from './roles.service';
import { RolesService } from './roles.service';
export * from './rutas.service';
import { RutasService } from './rutas.service';
export * from './solicitudesProduccion.service';
import { SolicitudesProduccionService } from './solicitudesProduccion.service';
export * from './usuarios.service';
import { UsuariosService } from './usuarios.service';
export const APIS = [FamiliaProductosService, LineasProduccionService, LoginService, MaestraFamiliaService, MaquinasService, ModulosRolesPermisosService, PlaneacionProduccionService, ProductosService, RestriccionDeLavadoService, RestriccionMaquinasService, RestriccionRutasService, RolesService, RutasService, SolicitudesProduccionService, UsuariosService];
