export * from './equipos.service';
import { EquiposService } from './equipos.service';
export * from './familiaProductos.service';
import { FamiliaProductosService } from './familiaProductos.service';
export * from './login.service';
import { LoginService } from './login.service';
export * from './maestraFamilia.service';
import { MaestraFamiliaService } from './maestraFamilia.service';
export * from './restriccionDeLavado.service';
import { RestriccionDeLavadoService } from './restriccionDeLavado.service';
export * from './restriccionEquipos.service';
import { RestriccionEquiposService } from './restriccionEquipos.service';
export * from './roles.service';
import { RolesService } from './roles.service';
export * from './rutas.service';
import { RutasService } from './rutas.service';
export * from './solicitudesProduccion.service';
import { SolicitudesProduccionService } from './solicitudesProduccion.service';
export * from './usuarios.service';
import { UsuariosService } from './usuarios.service';
export const APIS = [EquiposService, FamiliaProductosService, LoginService, MaestraFamiliaService, RestriccionDeLavadoService, RestriccionEquiposService, RolesService, RutasService, SolicitudesProduccionService, UsuariosService];
